services:
  postgres:
    image: 'postgres:latest'
    container_name: gameService
    environment:
      - 'POSTGRES_DB=Games'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=user'
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_games
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: